USE SUSHISTORE_MANAGEMENT
GO

CREATE OR ALTER TRIGGER GIAMONANLONHONK
ON DISH
AFTER INSERT, UPDATE
AS
IF UPDATE(Price)
BEGIN		
    IF EXISTS (SELECT * FROM DISH WHERE Price <0)
	BEGIN
		RAISERROR(N'LỖI NHẬP GIÁ NHỎ HƠN 0!',16,1)
		ROLLBACK
	END
END
GO

